name: Run Producer

on:
  # Can be manually triggered
  workflow_dispatch: {}
  # Triggered on each pull request to main
  push:
    branches: [ main ]

jobs:
  producer:
    runs-on: localhost
    #container:
      #image: python:3.9-bookworm

    steps:
      - name: Checkout code repository in agent
        uses: actions/checkout@v4
        with:
          set-safe-directory: true


      # Fix GIT ownership issues
      - name: Set ownership
        run: |
          # Fix GIT not liking owner of the checkout dir
          chown -R $(id -u):$(id -g) $PWD


      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9



      # Run Kafka producer
      - name: Run Kafka producer script
        run: |
          python scripts/customer_producer.py



      # Check if the script ran successfully
      - name: Check if the script ran successfully
        run: |
          echo "Script ran successfully"

          # Exit with 1 if the script failed
          exit 1





